name: Metrics
on:
  schedule: [{ cron: '0 */4 * * *' }]
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Activity
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          template: repository
          repo: mod-html
          filename: metrics/activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_activity: yes
          plugin_activity_limit: 1
          plugin_activity_visibility: public
          plugin_activity_timestamps: true
          plugin_activity_filter: all

      - name: Contributors
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          template: repository
          repo: mod-html
          filename: metrics/contributors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_contributors: yes
          plugin_contributors_contributions: yes

      - name: Followup
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          template: repository
          repo: mod-html
          filename: metrics/followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          template: repository
          repo: mod-html
          filename: metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 4

      - name: Compact display in base plugin
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          template: repository
          repo: mod-html
          filename: metrics/lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes

